### PR TITLE
Adding Jenkins pipeline for building this project on Jenkins

### PR DESCRIPTION
**Pull request by denmanveer**
Adding Jenkins pipeline for building this project on Jenkins locally

### CODE REVIEW

**Review by fnour — APPROVED** [review]
Looks good to me. Let's also create an identical PR for a `7.6.2-interset` branch. That's the elasticsearch version planned for interset 6.2.0

**Review by themoonraker13 — APPROVED** [review]
LGTM!

**Review by bdjahandideh — APPROVED** [review]
looks good to me as well

**Comment by denmanveer** [comment]
@fnour for sure, I will do that for the `7.6.2-interset` branch as well.

**Pull request merged**
