### PR TITLE
Adding Jenkins pipeline for building this project on Jenkins

### PR DESCRIPTION
**Pull request by denmanveer**
Adding Jenkins pipeline for building this project on Jenkins locally

### CODE REVIEW

**Review by themoonraker13 — APPROVED** [review]
LGTM! We should probably enable branch protection rules on release/critical branches.

**Review by fnour — APPROVED** [review]

**Comment by denmanveer** [comment]
> LGTM! We should probably enable branch protection rules on release/critical branches.

Hey @themoonraker13,
I have added the branch protection rules: https://github.com/MicroFocus/elasticsearch-hadoop/settings/branch_protection_rules/17866247

**Comment by themoonraker13** [comment]
Thanks, @manveer7. Let's do the same for other public repositories that we actively contribute to.

**Comment by denmanveer** [comment]
> Thanks, @manveer7. Let's do the same for other public repositories that we actively contribute to.

Roger that sir 👍

**Pull request merged**
